### ISSUE TITLE
Mode vampirisms for phazer: how should it work?

### ISSUE THREAD

**Issue by gigjozsa** [gigjozsa/sunblocker#15]
Currently phazer will only load daytime data, and also flag them accordingly. But actually all data could be considered for calculating the mean and rms but only day time data be flagged. What shall we do?

**Comment by KshitijT** [comment]
We can check out the effectiveness of using both night+day vs only day time data. But offhand I would say that what you have outlined above should be the default mode of operation (use night+day, flag only day), but perhaps both options could be available to be used according to the preference of the user.
